config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, only: [:index, :create]
  get 'portfolios/angular', to: 'portfolios#angular', as: 'angular_portfolio_items'
  get 'portfolios/ruby_on_rails', to: 'portfolios#ruby_on_rails', as: 'ruby_on_rails_portfolio_items'
  get 'portfolio/new', to: 'portfolios#new', as: 'new_portfolio'
  get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio'
  patch 'portfolio/:id', to: 'portfolios#update'
  delete 'portfolio/:id', to: 'portfolios#destroy'

  get 'about-henrique', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    enum status: { draft: 0, published: 1 }

    validates_presence_of :title, :body

    belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
    extend ActiveSupport::Concern

    def self.image_generator(height:, width:)
        "http://placehold.it/#{height}x#{width}"
    end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }

    extend FriendlyId
    friendly_id :title, use: :slugged
    validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

    def self.angular
        where(subtitle: "Angular")
    end

    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby On Rails") }

    after_initialize :set_defaults
    
    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
        self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
    end
end

app/models/skill.rb
class Skill < ApplicationRecord
    includes Placeholder

    validates_presence_of :title

    after_initialize :set_defaults

    def set_defaults
        self.badge ||= Placeholder.image_generator(height: '250', width: '250')
    end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates_presence_of :title

    has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
   if @blog.draft?
    @blog.published! 
   elsif @blog.published?
    @blog.draft!      
   end

    respond_to do |format|
      format.html { redirect_to blogs_path }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[ show edit update destroy ], except: %i[ new ]

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def ruby_on_rails
    @ruby_on_rails_portfolio_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @params = params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
    @portfolio_item = Portfolio.new(@params)
    respond_to do |format|
        if @portfolio_item.save
            format.html { redirect_to portfolios_path, notice: "Portfolio item #{@portfolio_item.title} has been created successfully." }
        else
            format.html { render :new }
        end
    end
  end

  def edit
  end

  def update
    @params = params.require(:portfolio).permit(:title, :subtitle, :body)
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(@params)
        format.html { redirect_to portfolio_path(@portfolio_item[:id]), notice: "#{@portfolio_item.title} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_name = @portfolio_item[:title]
    respond_to do |format|
      if @portfolio_item.destroy
        format.html { redirect_to portfolios_path, notice: "#{@portfolio_item.title} was successfully deleted." }
      else
        format.html { redirect_to portfolios_path, notice: "There was an error completing this action." }
      end
    end
  end

  private
  def set_portfolio_item
    @portfolio_item = Portfolio.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog.id) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPort</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<p>Find me in app/views/pages/home.html.erb</p>

<h2>Posts:</h2>

<p>
    <%= @posts.inspect %>
</p>

<h2>Skills:</h2>

<p>
    <%= @skills.inspect %>
</p>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<% if !notice.nil? %>
    <h3><%= notice %></h3>
<% end %>

<% @angular_portfolio_items.each do |portfolio_item| %>
    <h3>Title: <%= portfolio_item.title %></h3>
    <p>Subtitle: <%= portfolio_item.subtitle %></p>
    <p>Body: <%= portfolio_item.subtitle %></p>
    <%= image_tag portfolio_item.main_image if !portfolio_item.main_image.nil? %>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <ul>
        <li>
            <%= link_to "Edit item", edit_portfolio_path(portfolio_item) %>
        </li>
        <li>
            <%= link_to "View item", portfolio_path(portfolio_item) %>
        </li>
    </ul>
    <hr>
<% end %>

<%= link_to "See all", portfolios_path %>

app/views/portfolios/edit.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<% if !notice.nil? %>
    <h3><%= notice %></h3>
<% end %>

<%= link_to "Create new portfolio item", new_portfolio_path %>

<% @portfolio_items.each do |portfolio_item| %>
    <h3>Title: <%= portfolio_item.title %></h3>
    <p>Subtitle: <%= portfolio_item.subtitle %></p>
    <p>Body: <%= portfolio_item.subtitle %></p>
    <%= image_tag portfolio_item.main_image if !portfolio_item.main_image.nil? %>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <ul>
        <li>
            <%= link_to "Edit item", edit_portfolio_path(portfolio_item) %>
        </li>
        <li>
            <%= link_to "View item", portfolio_path(portfolio_item) %>
        </li>
    </ul>
    <hr>
<% end %>

app/views/portfolios/new.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/ruby_on_rails.html.erb
<h1>Ruby On Rails Portfolio Items</h1>

<% if !notice.nil? %>
    <h3><%= notice %></h3>
<% end %>

<% @ruby_on_rails_portfolio_items.each do |portfolio_item| %>
    <h3>Title: <%= portfolio_item.title %></h3>
    <p>Subtitle: <%= portfolio_item.subtitle %></p>
    <p>Body: <%= portfolio_item.subtitle %></p>
    <%= image_tag portfolio_item.main_image if !portfolio_item.main_image.nil? %>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <ul>
        <li>
            <%= link_to "Edit item", edit_portfolio_path(portfolio_item) %>
        </li>
        <li>
            <%= link_to "View item", portfolio_path(portfolio_item) %>
        </li>
    </ul>
    <hr>
<% end %>

<%= link_to "See all", portfolios_path %>

app/views/portfolios/show.html.erb
<h1>Portfolio Items</h1>

<% if !notice.nil? %>
    <p><%= notice %></p>
<% end %>

<h3>Title: <%= @portfolio_item.title %></h3>

<p>Subtitle: <%= @portfolio_item.subtitle %></p>

<p>Body: <%= @portfolio_item.subtitle %></p>

<%= image_tag @portfolio_item.main_image if !@portfolio_item.main_image.nil? %>

<%= image_tag @portfolio_item.thumb_image if !@portfolio_item.thumb_image.nil? %>

<h3>Technologies used: </h3>

<ul>
    <% @portfolio_item.technologies.each do |t| %>
        <li>
            <%= t.name %>
        </li>
    <% end %>
</ul>

<hr>

<h4>Navigation buttons </h4>

<ul>
    <li>
        <%= link_to "Edit item", edit_portfolio_path(@portfolio_item) %>
    </li>
    <li>
        <%= link_to "Delete item", portfolio_path(@portfolio_item), method: :delete, data: { confirm: "Are you sure you want to delete #{@portfolio_item.title} permanently?" } %>
    </li>
    <li>
        <%= link_to "See all", portfolios_path %>
    </li>
</ul>
<hr>